# Generated by Django 4.2.1 on 2023-07-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.TimeField()),
                ('es_entrega_domicilio', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SantiagoApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RutaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('pedidos', models.ManyToManyField(to='SantiagoApp.pedido')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SantiagoApp.repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(default='media/platos/imagen.jpg', upload_to='platos')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('descripcion', models.TextField(default=None)),
                ('categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='SantiagoApp.categoriaplato')),
                ('ingredientes', models.ManyToManyField(to='SantiagoApp.ingrediente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SantiagoApp.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='platos',
            field=models.ManyToManyField(to='SantiagoApp.plato'),
        ),
    ]
